---
- name: Configure VLAN Interface for MLAG
  eos_vlan:
    vlanid={{ mlag.local_if_vlan | regex_replace('\D+','') }}
    trunk_groups={{ mlag.mlag_trunk_group }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Create Vlan Interface for MLAG
  eos_interface:
    name={{ mlag.local_if_vlan }}
    description="{{ mlag.mlag_domain_id }} SVI"
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Configure VLAN Interface IP for MLAG
  eos_ipinterface:
    name={{ mlag.local_if_vlan }}
    address={{ mlag.local_if_ip_address }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Configure Interface Members of Port-Channel for MLAG
  eos_interface:
    name={{ item }}
    description="MLAG PEER CNX - {{ mlag.mlag_domain_id }}"
    enable={{ mlag.peer_link_enable }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: mlag.peer_link_members | default([])
  when: mlag.peer_link_members

- name: Configure Interface Members of Port-Channel for MLAG
  eos_portchannel:
    name={{ mlag.peer_link_if }}
    members={{ mlag.peer_link_members | join(',') }}
    lacp_mode={{ mlag.peer_link_lacp_mode }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag

- name: Configure switchport mode trunk on Port-Channel
  eos_config:
    section='interface {{ mlag.peer_link_if }}'
    command='switchport mode trunk'
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag

- name: Configure trunk group on Port-Channel
  eos_config:
    section='interface {{ mlag.peer_link_if }}'
    command='switchport trunk group {{ mlag.mlag_trunk_group }}'
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag

- name: Configure MLAG
  eos_mlag_config:
    domain_id={{ mlag.mlag_domain_id }}
    local_interface={{ mlag.local_if_vlan }}
    peer_address={{ mlag.peer_address }}
    peer_link={{ mlag.peer_link_if }}
    shutdown={{ mlag.mlag_shutdown }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag

- name: Disable Spanning Tree on MLAG Vlan
  eos_config:
    command='no spanning-tree vlan {{ mlag.local_if_vlan | regex_replace('\D+','') }}'
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag.local_if_disable_spanning_tree | default(false)
