---
- hosts: all
  gather_facts: no
  connection: local
  environment:
    PYTHONPATH: '/usr/local/lib/python2.7/dist-packages/'

  roles:
    - { role: reset }
    - { role: upgrade, target_version: 4.15.6M }
