---
- hosts: webinar_lab
  gather_facts: no
  connection: local

  tasks:
    - block:
      - name: Find VM by name
        eos_command:
           commands:
              - command: 'show vmtracer vm name {{ id }}'
                output: 'json'
           provider: "{{ provider }}"
        register: output

      - set_fact: vm_output: "{{ output.stdout[0]['vms'] }}"
      when: '"{{ id_type }}" == "vm_name"'

    - block:
      - name: Find VM by Mac Addresss
        eos_command:
           commands:
              - command: 'show vmtracer vm mac {{ id }}'
                output: 'json'
           provider: "{{ provider }}"
        register: output

      - set_fact: vm_output: "{{ output.stdout[0]['vms'] }}"
      when: '"{{ id_type }}" == "mac_address"'

    - block:
      - name: Find VMs on a Given Interface
        eos_command:
          commands:
             - 'show vmtracer interface {{ id }}'
          provider: "{{ provider }}"
        register: output

      - set_fact: vm_output: "{{ output.stdout[0]['vms'] }}"
      when: '"{{ id_type }}" == "interface"'

    - block:
        - name: Find VMs on a given vlan
          eos_command:
             commands:
                - 'show vmtracer vm'
             provider: "{{ provider }}"
          register: vms

        - set_fact: vm_output: "{{ vms.stdout[0] | filter_vms(id) }}"

      when: ' "{{ id_type }}" == "vlan"'

    - debug: var=vm_output
