---
- name: Configure Arista VARP Mac Address
  eos_varp:
    mac_address={{ virtual_mac_addr|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: virtual_mac_addr is defined

- name: Configure Arista VARP VLAN resources
  eos_vlan:
    vlanid={{ item.vlanid }}
    name={{ item.name }}
    enable={{ item.enable|default('true') }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: varp_interfaces
  when: item.vlanid is defined

- name: Configure Arista VARP VLAN Interface
  eos_interface:
    name="Vlan{{ item.vlanid|mandatory }}"
    description="{{ item.description|default(omit) }}"
    enable={{ item.enable|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: varp_interfaces
  when: item.vlanid is defined

- name: Configure Arista VARP VLAN IP interface
  eos_ipinterface:
    name="Vlan{{ item.vlanid|mandatory }}"
    address={{ item.interface_addr }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: varp_interfaces
  when: item.interface_addr is defined

- name: Configure EOS VARP Interface Shared IP(s)
  eos_varp_interface:
    name="Vlan{{ item.vlanid|mandatory }}"
    shared_ip="{{ item.virtual_addrs|default([])|join(',') or omit }}"
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: varp_interfaces is defined
  with_items: varp_interfaces
