---
- name: Configure Arista EOS VLAN resources
  eos_vlan:
    vlanid={{ item.vlanid }}
    name={{ item.name }}
    enable={{ item.enable|default('true') }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: vlans
  when: vlans is defined
  register: eos_vlan_results

- name: Purge VLANs
  eos_purge:
    resource=eos_vlan
    results='{{ eos_vlan_results|to_nice_json }}'
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: eos_purge_vlans and vlans is defined


- name: Configure Arista EOS switchport resources
  eos_switchport:
    name={{ item.name }}
    mode={{ item.mode|default(omit) }}
    access_vlan={{ item.access_vlan|default(omit) }}
    trunk_native_vlan={{ item.trunk_native_vlan|default(omit) }}
    trunk_allowed_vlans={{ item.trunk_allowed_vlans|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: eos_switchports
  when: eos_switchports is defined
