---
- name: Configure Arista EOS VLAN resources
  eos_vlan:
    vlanid={{ item.vlanid }}
    name={{ item.name }}
    enable={{ item.enable|default('true') }}
    username={{ eapi.username|default(omit) }}
    password={{ eapi.password|default(omit) }}
    enablepwd={{ eapi.enablepwd|default(omit) }}
    transport={{ eapi.transport|default(omit) }}
    connection={{ eapi.connection|default(omit) }}
    config={{ eapi.config|default(omit) }}
    host={{ eapi.host|default(omit) }}
    port={{ eapi.port|default(omit) }}
    debug={{ eos.debug|default(omit) }}
  with_items: vlans
  when: vlans is defined
  register: eos_vlan_results

- name: Purge VLANs
  eos_purge:
    resource=eos_vlan
    results='{{ eos_vlan_results|to_nice_json }}'
    username={{ eapi.username|default(omit) }}
    password={{ eapi.password|default(omit) }}
    enablepwd={{ eapi.enablepwd|default(omit) }}
    transport={{ eapi.transport|default(omit) }}
    connection={{ eapi.connection|default(omit) }}
    config={{ eapi.config|default(omit) }}
    host={{ eapi.host|default(omit) }}
    port={{ eapi.port|default(omit) }}
    debug={{ eos.debug|default(omit) }}
  when: purge_vlans and vlans is defined


- name: Configure Arista EOS switchport resources
  eos_switchport:
    name={{ item.name }}
    mode={{ item.mode|default(omit) }}
    access_vlan={{ item.access_vlan|default(omit) }}
    trunk_native_vlan={{ item.trunk_native_vlan|default(omit) }}
    trunk_allowed_vlans={{ item.trunk_allowed_vlans|default(omit) }}
    username={{ eapi.username|default(omit) }}
    password={{ eapi.password|default(omit) }}
    enablepwd={{ eapi.enablepwd|default(omit) }}
    transport={{ eapi.transport|default(omit) }}
    connection={{ eapi.connection|default(omit) }}
    config={{ eapi.config|default(omit) }}
    host={{ eapi.host|default(omit) }}
    port={{ eapi.port|default(omit) }}
    debug={{ eos.debug|default(omit) }}
  with_items: eos_switchports
  when: eos_switchports is defined
