---
- name: Gather Show Version Facts
  eos_command:
    commands:
      - 'show version | json'
    provider: '{{ provider }}'
  register: showvers

- set_fact: perform_upgrade={{ target_version not in showvers['stdout'][0]['version'] }}

- name: Install new SWI
  eos_command:
    commands:
      - 'install source {{ swi_url }} now'
    provider: '{{ provider }}'
  when: perform_upgrade

- name: Reload the Switch
  eos_command:
    commands:
      - 'reload now'
    provider: '{{ provider }}'
  when: perform_upgrade

- name: Wait for switch to come back online
  wait_for:
    host={{ inventory_hostname }}
    delay={{ install_pause }}
    port=80
    timeout={{ reboot_timer | default(300) }}
  when: perform_upgrade

- pause: seconds=5
  when: perform_upgrade

- name: Gather Show Version Facts
  eos_command:
    commands:
      - 'show version | json'
    provider: '{{ provider }}'
  register: showvers_post
  when: perform_upgrade

- name: Check EOS Version
  assert:
    that:
      - "'{{ target_version }}' in showvers_post['stdout'][0]['version']"
  when: perform_upgrade
