---
- name: Gather Routing Table
  eos_command:
    commands:
      - 'show ip route summary'
    provider: '{{ provider }}'
  register: routeoutput

- name: Check Route Table Output
  assert:
    that:
      "0 < routeoutput['stdout'][0]['totalRoutes']"

