---
- name: Gather IPs from Host vars
  set_fact:
    ips: '{{ ansible_play_hosts | gather_ips(hostvars) }}'

- name: Run Ping tests
  eos_command:
    commands:
      - 'ping {{ item.address }} repeat 1'
    provider: '{{ provider }}'
  with_items: "{{ ips }}"
  register: pingresults

- name: Validate Ping Tests
  assert:
    that:
        "'0% packet loss' in {{item.value.stdout.messages}}"

    msg: "Packet Loss seen"
  with_dict: "{{ pingresults }}"
