---
- name: Gather Routing Table
  eos_command:
    commands:
      - 'show ip route'
    provider: '{{ provider }}'
  register: routeoutput

- name: Run Ping tests
  eos_command:
    commands:
      - 'ping {{ item.ip_interfaces.address }} repeat 1'
    provider: '{{ provider }}'
    with: '{{ inventory_hosts }}'
  register: pingresults  
