---
- name: Revert the EOS Running Configuration to a default state
  eos_command:
    commands='configure replace {{ default_config }} force'
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: default_config is defined
