---
- name: Configure Arista EOS Hostname
  eos_system:
    hostname={{ hostname|default(omit) }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: hostname is defined

- name: Configure Arista EOS IP Routing
  eos_system:
    ip_routing={{ eos_ip_routing_enabled }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: eos_ip_routing_enabled is defined

- name: Configure Arista EOS CLI Users
  eos_user:
    name={{ item.name|default(omit) }}
    encryption={{ item.encryption|default(omit) }}
    secret={{ item.secret|default(omit) }}
    nopassword={{ item.nopassword|default(omit) }}
    privilege={{ item.privilege|default(omit) }}
    role={{ item.role|default(omit) }}
    sshkey={{ item.sshkey|default(omit) }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: eos_users is defined
  with_items: eos_users
