---
- name: Gather show version output
  eos_command:
   commands:
    - 'show version'
   provider: "{{ provider }}"
  register: showver

- name: Check that this host meets the bug signature
  assert: 
    that:
       - "'{{ bugs.versions[0] }}' in '{{ showver['stdout'][0]['version'] }}'" 
       - "'{{ bugs.platform[0] }}' in '{{ showver['stdout'][0]['modelName'] }}'"
    msg: "This host is not a candiate for this bug"

- set_fact:
   index: "{{ bugs.command_info.attr}}"
   key: "{{ bugs.command_info.key}}"


- name: Run bug verification command
  eos_command:
    commands:
      - '{{ bugs.command_info.cmd }}'
    provider: "{{ provider }}"
  register: bugout

- name: Comparing bug output
  assert:
    that:
      - '"{{ bugs.output }}" not in "{{ item[index] }} "'
    msg: 'This host IS a candiate for "{{ bugs.name}}"'
  with_items: "{{ bugout['stdout'][0][key] }}"

    
