---
- name: configure BGP global parameters
  eos_bgp_config:
    bgp_as={{ bgp.bgp_as|default(omit) }}
    enable={{ bgp.enable|default(omit) }}
    router_id={{ bgp.router_id|default(omit) }}
    maximum_paths={{ bgp.maximum_paths|default(omit) }}
    maximum_ecmp_paths={{ bgp.maximum_ecmp_paths|default(omit) }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: bgp is defined and bgp.enable

- name: configure BGP neighbors
  eos_bgp_neighbor:
    name={{ item.name }}
    remote_as={{ item.remote_as|default(omit) }}
    enable={{ item.enable|default(omit) }}
    description={{ item.description|default(omit) }}
    next_hop_self={{ item.next_hop_self|default(omit) }}
    peer_group={{ item.peer_group|default(omit) }}
    route_map_in={{ item.route_map_in|default(omit) }}
    route_map_out={{ item.route_map_out|default(omit) }}
    send_community={{ item.send_community|default(omit) }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: bgp.neighbors
  when: bgp.neighbors is defined and bgp.enable
  register: eos_bgp_neighbor_result

- name: set BGP redistribute setting
  eos_config:
    section='router bgp {{ bgp.bgp_as }}'
    regexp='(?<!no )redistribute {{ item }}'
    command='redistribute {{ item }}'
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: bgp.redistribute is defined and bgp.enable
  with_items: bgp.redistribute | default([])

- name: set BGP log neighbor changes
  eos_config:
    section='router bgp {{ bgp.bgp_as }}'
    regexp='(?<!no )bgp log-neighbor-changes'
    command='bgp log-neighbor-changes'
    username={{ eos_eapi_username|default(omit) }}
    config={{ eos_eapi_config|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: bgp.log_neighbor_changes and bgp.enable
  register: bgp_output

- name: set BGP timers
  eos_config:
    section='router bgp {{ bgp.bgp_as }}'
    command='timers bgp {{ bgp.timers.keep_alive }} {{ bgp.timers.hold }}'
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: bgp.timers is defined and bgp.enable

- name: set BGP listeners
  eos_config:
    section='router bgp {{ bgp.bgp_as }}'
    command='bgp listen range {{ item.name }} peer-group {{ item.peer_group }} remote-as {{ item.remote_as }}'
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: bgp is defined and bgp.enable and bgp.listeners
  with_items: bgp.listeners | default([])

- name: purge BGP neighbors
  eos_purge:
    resource=eos_bgp_neighbor
    results='{{ eos_bgp_neighbor_result|to_nice_json }}'
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: eos_bgp_neighbor_result is defined and
        (bgp.enable and eos_purge_bgp_neighbors)

- name: configure BGP networks
  eos_bgp_network:
    prefix={{ item.prefix }}
    masklen={{ item.masklen }}
    route_map={{ item.route_map|default(omit) }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: bgp.networks
  when: bgp.networks is defined and bgp.enable
  register: eos_bgp_network_result

- name: purge BGP networks
  eos_purge:
    resource=eos_bgp_network
    results='{{ eos_bgp_network_result|to_nice_json }}'
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: eos_bgp_network_result is defined and
        (bgp.enable and eos_purge_bgp_networks)
